name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: dsp-testing/dependency-review-action@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
