# This is a basic workflow to help you get started with Actions

name: Excel Report

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repos: [ 'dsp-testing/verdaccio', 'dsp-testing/ghas-intro-6' ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Generate issues and save results
    - uses: amitgupta7/ghas-reports-action@v3.4
      with:
        token: ${{ secrets.SECURITY_TOKEN }}
        repo: ${{ matrix.repos }}

    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: alerts.xlsx   
