name: GHAS-Events-CI

on:
  schedule:
    # Run this every hour
    - cron:  '0 * * * *'
  workflow_dispatch :
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: print date
        run: echo `date`
        
      - uses: actions/github-script@v5
        with:
          script: |
            const secret_alerts = await github.request('GET /repos/{owner}/{repo}/secret-scanning/alerts', 
            {
              owner: context.repo.owner,
              name: context.repo.repo
            });
            console.log(secret_alerts)
