name: GHAS-Events-CI

on:
  push:
    branches: [ main ]
  schedule:
    # Run this every hour
    - cron:  '0 * * * *'
  workflow_dispatch :
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: print date
        run: echo `date`
        
      - uses: actions/github-script@v5
        with:
          script: |
            const opts = github.rest.secretScanning.listAlertsForRepo({
                context.repo.owner,
                context.repo.repo
              })
            const issues = await github.paginate(opts)
            for (const issue of issues) {
                console.log(issue)
              }  
